import { Inter } from "next/font/google";
import "./globals.css";
import AppHeader from "./components/AppHeader/page";
import AppFooter from "./components/AppFooter/page";
import AppContainer from "./components/AppContainer/page";
import Nav from "./components/nav/page";
import Script from "next/script";
import 'flowbite';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({ children }) {

	return (
		<html lang="en">
			<body className={`${inter.className} my-16`}>
				<Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></Script>
				<Nav />
				<AppContainer>{children}</AppContainer>
				<AppFooter />
			</body>
		</html>
	);
}
